# Generated by Django 3.2.9 on 2024-07-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Insurers', '0006_auto_20240702_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=255)),
                ('policies', models.TextField()),
                ('quote', models.TextField()),
            ],
        ),
    ]
