# Generated by Django 4.2.8 on 2024-08-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_qfquestions_qfsubcategory_questionnaireformcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOfQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=255)),
                ('input_value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'qf_questions',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='qfquestions',
            options={},
        ),
    ]
