# Generated by Django 4.2.8 on 2024-08-13 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_answerofq_alter_qfquestions_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='qfquestions',
            table=None,
        ),
    ]
