# Generated by Django 4.2.8 on 2024-08-13 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_qfquestions_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answerofq',
            table='qf_answers',
        ),
    ]
