# Generated by Django 4.2.8 on 2024-08-13 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_answerofq_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerOfQ',
        ),
        migrations.AlterModelOptions(
            name='qfquestions',
            options={'managed': False},
        ),
    ]
