# Generated by Django 4.2.8 on 2024-08-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_qfquestions_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='QFAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=255)),
                ('input_value', models.TextField()),
            ],
        ),
    ]
