# Generated by Django 3.2.9 on 2024-07-02 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insurers', '0005_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfileQuote',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
