# Generated by Django 3.2.9 on 2024-05-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_userprofile_policies_userprofile_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('scope', models.TextField()),
                ('policies', models.CharField(default='Belirtilmemiş', max_length=100)),
                ('quote', models.CharField(default='Belirtilmemiş', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
