# Generated by Django 4.2.8 on 2024-08-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QFQuestions',
            fields=[
                ('qfq_id', models.AutoField(primary_key=True, serialize=False)),
                ('qfq_sort_number', models.IntegerField()),
                ('qsc_id', models.IntegerField()),
                ('question', models.TextField()),
                ('radio', models.IntegerField(blank=True, null=True)),
                ('radio_option1', models.TextField(blank=True, null=True)),
                ('radio_option2', models.TextField(blank=True, null=True)),
                ('radio_option3', models.TextField(blank=True, null=True)),
                ('radio_option4', models.TextField(blank=True, null=True)),
                ('inputName', models.TextField(blank=True, null=True)),
                ('input_type', models.TextField(blank=True, null=True)),
                ('inputName2', models.TextField(blank=True, null=True)),
                ('input_type2', models.TextField(blank=True, null=True)),
                ('inputName3', models.TextField(blank=True, null=True)),
                ('input_type3', models.TextField(blank=True, null=True)),
                ('currentSelection', models.TextField(blank=True, null=True)),
                ('textarea', models.TextField(blank=True, null=True)),
                ('placeholder', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qf_questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QFSubCategory',
            fields=[
                ('qsc_id', models.AutoField(primary_key=True, serialize=False)),
                ('qsc_sort_number', models.IntegerField(unique=True)),
                ('qsc_name', models.CharField(max_length=255, unique=True)),
                ('qsc_color', models.CharField(blank=True, max_length=255, null=True)),
                ('qsc_json_title', models.TextField()),
                ('accordion_id', models.TextField()),
                ('accordion_input', models.TextField()),
                ('accordion_label', models.TextField()),
                ('accordion_divClass', models.TextField()),
                ('accordion_label_id', models.TextField()),
                ('accordion_item_desc', models.TextField()),
            ],
            options={
                'db_table': 'qf_sub_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireFormCategory',
            fields=[
                ('qfc_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('default_qsc_id', models.TextField(blank=True, null=True)),
                ('additional_qsc_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'questionnaire_form_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FormVerisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('teklif_no', models.CharField(max_length=100)),
                ('sigortali_adi', models.CharField(max_length=100)),
                ('vkn', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
