# Generated by Django 4.2.8 on 2024-04-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_industry_company_logo_company_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='scope',
            field=models.TextField(),
        ),
    ]
