# Generated by Django 4.2.8 on 2024-04-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_company_logo_alter_company_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='policies',
            field=models.CharField(default='Belirtilmemiş', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='quote',
            field=models.CharField(default='Belirtilmemiş', max_length=100),
        ),
    ]
